using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Oblivion.HabboHotel.Items.Wired
{
    public enum WiredBoxType
    {
        None,
        TriggerRoomEnter,
        TriggerUserSays,
        TriggerRepeat,
        TriggerLongRepeat,
        TriggerStateChanges,
        TriggerWalkOnFurni,
        TriggerWalkOffFurni,
        TriggerGameStarts,
        TriggerGameEnds,
        TriggerUserFurniCollision,
        TriggerUserSaysCommand,
        TriggerAtGivenTime,
        TriggerBotReachUser,
        TriggerBotReachFurni,

        EffectShowMessage,
        EffectShowMessageNux,
        EffectShowMessageCustom,
        EffectTeleportToFurni,
        EffectToggleNegativeFurniState,
        EffectToggleFurniState,
        EffectKickUser,
        EffectMatchPosition,
        EffectMoveAndRotate,
        EffectMoveFurniToNearestUser,
        EffectMoveFurniFromNearestUser,
        EffectMuteTriggerer,
        EffectGiveReward,
        EffectExecuteWiredStacks,
        EffectAddScore,
        EffectAddScore2,
        EffectAddRewardPoints,
        EffectApplyClothes,
        EffectMoveUser,
        EffectTimerReset,
        EffectMoveToDir,
        EffectProgressUserAchievement,
        EffectSendYouTubeVideo,
        EffectFixRoom,

        EffectTeleportBotToFurniBox,
        EffectBotChangesClothesBox,
        EffectBotMovesToFurniBox,
        EffectBotCommunicatesToAllBox,
        EffectBotCommunicatesToUserBox,
        EffectBotFollowsUserBox,
        EffectBotGivesHanditemBox,

        EffectAddActorToTeam,
        EffectRemoveActorFromTeam,
        EffectSetRollerSpeed,
        EffectRegenerateMaps,
        EffectGiveUserBadge,
        EffectEnableUserHandItem,
        EffectEnableUserEffect,
        EffectEnableUserDance,
        EffectUserFastWalk,
        EffectGiveUserFreeze,
        EffectGiveUserDiamonds,
        EffectGiveUserDuckets,
        EffectGiveUserCredits,
        TriggerScoreAchieved,

        ConditionFurniHasUsers,
        ConditionFurniHasFurni,
        ConditionTriggererOnFurni,
        ConditionIsGroupMember,
        ConditionIsNotGroupMember,
        ConditionTriggererNotOnFurni,
        ConditionFurniHasNoUsers,
        ConditionIsWearingBadge,
        ConditionIsWearingFX,
        ConditionIsNotWearingBadge,
        ConditionIsNotWearingFX,
        ConditionMatchStateAndPosition,
        ConditionDontMatchStateAndPosition,
        ConditionUserCountInRoom,
        ConditionUserCountDoesntInRoom,
        ConditionFurniTypeMatches,
        ConditionFurniTypeDoesntMatch,
        ConditionFurniHasNoFurni,
        ConditionActorHasHandItemBox,
        ConditionActorHasNotHandItemBox,
        ConditionActorIsInTeamBox,
        ConditionActorIsNotInTeamBox,
        ConditionWearingClothes,
        ConditionNotWearingClothes,
        ConditionDateRangeActive,
        ConditionLessSecs,
        ConditionMoreSecs,
        SendCustomMessageBox,
        TotalUsersCoincidence,

        AddonRandomEffect,

        // CUSTOM WIREDS
        EffectLowerFurni,
        EffectRaiseFurni,
        EffectRoomForward,
        ConditionActorHasDiamonds,
        ConditionActorHasNotDiamonds,
        ConditionActorHasDuckets,
        ConditionActorHasNotDuckets,
        ConditionActorHasRank,
        ConditionActorHasNotRank,
        ConditionActorHasNotCredits,
    }
}